### ISSUE TITLE
Fout bij ophalen van weerlive data

### ISSUE THREAD

**Issue by PRoomberg** [idurz/Indigo-Weerlive#1]
Sinds enkele dagen haalt de plugin geen data meer op.
In Indigo wordt dit in de log getoond:

`   WeerLive Error                  Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 763, in runConcurrentThread
  File "plugin.py", line 283, in handle_weerlive
AttributeError: 'SSLError' object has no attribute 'code'

   WeerLive Error                  plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
`

**Comment by PRoomberg** [comment]
In handle_weerlive heb ik de exception handling gewijzigd.

        self.verbose("Weerlive Get ended with {}".format(e))

in plaats van 

        self.verbose("Weerlive Get ended with {}".format(e.code))

En dat geeft nu een betere foutmelding in Indigo:

Weerlive Get ended with [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**Comment by idurz** [comment]
Changed the code to handle exceptions in version 1.1.1. according to the above
